apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow
type: Opaque
data:
  DB_PASSWORD: c2hvcGZsb3cxMjM=
  JWT_SECRET: c2hvcGZsb3dqd3RzZWNyZXRrZXkyMDI0
---
apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow-infra
type: Opaque
data:
  DB_PASSWORD: c2hvcGZsb3cxMjM=
  POSTGRES_PASSWORD: c2hvcGZsb3cxMjM=