server.port=3003
spring.application.name=order-service

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/orderdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:shopflow}
spring.datasource.password=${DB_PASSWORD:shopflow123}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka Producer Config
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Disable Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration